export const FETCH_DATA_START = 'FETCH_DATA_START';



export const LATEST_PICS_START = 'LATEST_PICS_START';
export const LATEST_PICS_SUCCESS = 'LATEST_PICS_SUCCESS';
export const LATEST_PICS_FAIL = 'LATEST_PICS_FAIL';

export const RANDOM_PICS_START = 'RANDOM_PICS_START';
export const RANDOM_PICS_SUCCESS = 'RANDOM_PICS_SUCCESS'
export const RANDOM_PICS_FAIL = 'RANDOM_PICS_FAIL'

export const TOP_PICS_START = 'TOP_PICS_START';
export const TOP_PICS_SUCCESS = 'TOP_PICS_SUCCESS'
export const TOP_PICS_FAIL = 'TOP_PICS_FAIL'

export const HOT_PICS_START = 'HOT_PICS_START';
export const HOT_PICS_SUCCESS = 'HOT_PICS_SUCCESS'
export const HOT_PICS_FAIL = 'HOT_PICS_FAIL'

// All available tags
export const TAGS_START = 'TAGS_SUCCESS'
export const TAGS_SUCCESS = 'TAGS_SUCCESS'
export const TAGS_FAIL = 'TAGS_FAIL'

// All pics with a certain tag
export const TAG_PICS_START = 'TAG_PICS_START'
export const TAG_PICS_SUCCESS = 'TAG_PICS_SUCCESS'
export const TAG_PICS_FAIL = 'TAG_PICS_FAIL'

export const TAG_SUGGESTION_SUCCESS = 'TAG_SUGGESTION_SUCCESS'
export const TAG_SUGGESTION_FAIL = 'TAG_SUGGESTION_FAIL'

export const CREATE_PICS_SUCCESS = 'CREATE_PICS_SUCCESS'
export const CREATE_PICS_FAIL = 'CREATE_PICS_FAIL'
export const PICS_UPLOAD_PROGRESS = 'PICS_UPLOAD_PROGRESS'

export const SEARCH_START = 'SEARCH_START'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const SEARCH_FAIL = 'SEARCH_FAIL'
export const SEARCH_CLEAR = 'SEARCH_CLEAR';

export const AUTHOR_PICS_FAIL = 'AUTHOR_PICS_FAIL'
export const AUTHOR_PICS_SUCCESS = 'AUTHOR_PICS_SUCCESS'

export const SAVED_PICS_FAIL = 'SAVED_PICS_FAIL'
export const SAVED_PICS_SUCCESS = 'SAVED_PICS_SUCCESS'

export const SAVE_SUCCESS = 'SAVE_SUCCESS'
export const SAVE_FAIL = 'SAVE_FAIL'

export const LIKE_SUCCESS = 'LIKE_SUCCESS'
export const LIKE_FAIL = 'LIKE_FAIL'

export const DETAIL_START = 'DETAIL_START'
export const DETAIL_FAIL = 'DETAIL_FAIL'
export const DETAIL_SUCCESS = 'DETAIL_SUCCESS'

export const DELETE_SUCCESS = 'DELETE_SUCCESS'
export const DELETE_FAIL = 'DELETE_FAIL'



export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const CHECK_AUTH_SUCCESS = 'CHECK_AUTH_SUCCESS';
export const CHECK_AUTH_FAIL = 'CHECK_AUTH_FAIL';



export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAIL = 'PROFILE_FAIL';

export const PROFILE_UPDATE_FAIL = 'PROFILE_UPDATE_FAIL';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';

export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const USER_DATA_SUCCESS = 'USER_SUCCESS';
export const USER_DATA_FAIL = 'USER_FAIL';



export const RESET_PARAMETER = 'RESET_PARAMETER';
export const SET_Q = 'SET_Q';
export const SET_TOP_RANGE = 'SET_TOP_RANGE';

export const RESET_SIDE_BAR = 'RESET_SIDE_BAR';
export const RESET_PICS_ITEMS = 'RESET_PICS_ITEMS';

export const HOLD_SIDE_BAR = 'HOLD_SIDE_BAR';
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE"
export const SET_PAGE = "SET_PAGE"

export const SET_AUTHOR = "SET_AUTHOR"
