export const PICS_SUCCESS = 'PICS_SUCCESS';
export const PICS_FAIL = 'PICS_FAIL';
export const TAG_PICS_SUCCESS = 'TAG_PICS_SUCCESS'
export const TAG_PICS_FAIL = 'TAG_PICS_FAIL'
export const CREATE_PICS_SUCCESS = 'CREATE_PICS_SUCCESS'
export const CREATE_PICS_FAIL = 'CREATE_PICS_FAIL'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const SEARCH_FAIL = 'SEARCH_FAIL'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const CHECK_AUTH_SUCCESS = 'CHECK_AUTH_SUCCESS';
export const CHECK_AUTH_FAIL = 'CHECK_AUTH_FAIL';



export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAIL = 'PROFILE_FAIL';
export const PROFILE_UPDATE_FAIL = 'PROFILE_UPDATE_FAIL';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';


export const RESET_PARAMETER = 'RESET_PARAMETER';
export const SET_Q = 'SET_Q';

export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE"
export const SET_PAGE = "SET_PAGE"