# Generated by Django 4.2.5 on 2023-10-03 23:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('thumb', models.ImageField(blank=True, default='default.png', upload_to='media')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 10, 3, 23, 39, 37, 835787, tzinfo=datetime.timezone.utc))),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('saved_pic', models.ManyToManyField(blank=True, related_name='save_pic', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='tags', to='posts.hashtag')),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
