# Generated by Django 4.2.5 on 2023-10-16 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_delete_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 5, 58, 1, 415025, tzinfo=datetime.timezone.utc)),
        ),
    ]
