# Generated by Django 4.2.5 on 2023-11-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumb',
            field=models.ImageField(blank=True, upload_to='thumb'),
        ),
    ]
