# Generated by Django 4.2.5 on 2023-11-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='tag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
