# Generated by Django 3.2.20 on 2024-03-22 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_remove_post_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
