# Generated by Django 5.0.4 on 2024-05-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='watched',
            field=models.ManyToManyField(blank=True, related_name='watched', to='posts.visit'),
        ),
    ]
