# Generated by Django 5.0.4 on 2024-05-05 07:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_remove_post_watched'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='watched',
            field=models.ManyToManyField(blank=True, related_name='watched', to=settings.AUTH_USER_MODEL),
        ),
    ]
