# Generated by Django 4.2.5 on 2023-11-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile/cover'),
        ),
    ]
