# Generated by Django 3.2.20 on 2024-03-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_images/cover'),
        ),
    ]
