# Generated by Django 3.2.20 on 2024-03-21 13:27

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover',
            field=models.ImageField(default='cover_default.jpg', null=True, upload_to='profile_images/cover'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_default.jpg', null=True, upload_to=users.models.upload_to),
        ),
    ]
